### ISSUE TITLE
How to find base folder for AMD packages

### ISSUE THREAD

**Issue by stdavis** [agrc/atom-amdbutler#1]
We need a way to determine the name of the folder to crawl for packages.

We can assume that it's a parent of the current file. That's about it.

This was stored in the project settings file and/or in the plugin settings file in the Sublime version. There is no project file available in the atom environment and I'm not sure that it's a great solution to just store one folder name in the package settings for all of your projects.

Maybe we could store a list of folder names at the package level that the user could manage and look for those as parents of the current folder?

@steveoh any ideas?

**Comment by steveoh** [comment]
so are you proposing a list of folders to look for packages? For instance, `src`, `libs`, `vendor`, `libraries`, etc? Then start from the working directory and move up to find one of these?

**Comment by stdavis** [comment]
Yes. Although I would say it is a list of folder. Not sure what you mean by
a tree.

On Mon, Jul 13, 2015 at 9:12 AM, steveoh notifications@github.com wrote:

> so are you proposing a tree of folders to look for packages? For instance,
> src, libs, vendor, libraries, etc? Then start from the working directory
> and move up to find one of these?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/atom-amdbutler/issues/1#issuecomment-120962608.

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC

**Comment by steveoh** [comment]
so the way i'm doing it is from the project down, and is slow depending on how many packages you have. I think to speed that up we need to make some string assumptions. Like we aren't going to look more than 3 or 4 folders deep. That seems pretty normal for folder structure. Maybe put it in a config or something.

**Comment by stdavis** [comment]
I think that bottom up is working ok.
