### ISSUE TITLE
View

### ISSUE THREAD

**Issue by steveoh** [agrc/atom-amdbutler#2]
Create the view for getting the user input and filtering the file list.

This looks a lot easier to do in coffee script. Maybe the view can be coffee and the rest js?

[this](https://github.com/rpowelll/gist-it/tree/master/lib) is a decent example on user input.

**Comment by stdavis** [comment]
I'd rather see it stay all JS if possible. What's easier about it? Just that the examples are in coffee script? 

If it becomes a huge pain to write this project in JS then I'd be open to switching but I'm not super excited about having it piecemeal.
