### ISSUE TITLE
Removes $ if variable

### ISSUE THREAD

**Issue by mokkabonna** [agrc/atom-amdbutler#21]
If I have a variable in an import list named $ (typically jquery) it gets removed and causes sorting to go wrong.

``` js
define([
  'jquery',
  'knockout'
], function(
  $,
  ko
){
  'use strict';
});
```

**alt-s** => 

``` js
define([
  'jquery',
  'knockout'
], function(
  ko
){
  'use strict';
});
```

It also does this (removes the $ if part of variable name):

``` js
define([
  'jquery',
  'knockout'
], function(
  $jquery,
  ko
){
  'use strict';

  $jquery.ajax(...)
});
```

=> 

``` js
define([
  'jquery',
  'knockout'
], function(
  jquery,
  ko
){
  'use strict';

  $jquery.ajax(...) //now undefined
});
```

This regex should probably be updated to match javascript variable names. https://github.com/agrc/atom-amdbutler/blob/master/lib/zipper.js#L3

http://stackoverflow.com/a/9337047/94394

But as the answer says, it can be alot, and the regex for that is long. Maybe use something like https://www.npmjs.com/package/is-var-name

Although maybe anything should be ok? If you mutate the variable names that are there other parths of the code will get problems unless you do it 100% correct (since it might remove or rename as shown above). 

I think maybe this tool should just make sure the ordering of the existing variable names are preserved. Other tools should validate them imo, like jshint. 

**If so I would assume a `split(',')` and `trim()` each is enough to get the proper names.**

**Comment by stdavis** [comment]
Nice catch. Definitely a bug.

I agree that it's outside of the scope of this tool to validate parameter names. I don't believe that `is-var-name` would be an option for us since it uses the `Function` constructor which is blocked by electron. 

`split`/`trim` sounds like the way to go.
